---
- name: Configuration server
  block: 
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - python3-dev
        - python3-setuptools
        - python3-wheel
        - python3-apt
        - python3-docker
        - docker.io
    - name: Update system
      apt:
        update_cache: yes
    